spring.application.name=ms-rutaexpress-shipments
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

rutaexpress.catalog.base-url=${CATALOG_BASE_URL:http://localhost:8082}
rutaexpress.catalog.capacity-path=${CATALOG_CAPACITY_PATH:/api/catalog/services/{serviceId}/capacity/decrement}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
rutaexpress.security.jwk-set-uri=${AZURE_JWK_SET_URI:}
