spring.application.name=ms-rutaexpress-shipments
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

rutaexpress.catalog.base-url=${CATALOG_BASE_URL:http://localhost:8082}
rutaexpress.catalog.capacity-path=${CATALOG_CAPACITY_PATH:/api/catalog/services/{serviceId}/capacity/decrement}
rutaexpress.catalog.connect-timeout=${CATALOG_CONNECT_TIMEOUT:3s}
rutaexpress.catalog.read-timeout=${CATALOG_READ_TIMEOUT:10s}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
rutaexpress.security.audience=${AZURE_AUDIENCE}
rutaexpress.security.jwk-set-uri=${AZURE_JWK_SET_URI:}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
server.error.include-message=never
server.error.include-stacktrace=never
